import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import SessionWrapper from "./Components/SessionWrapper"
import SocketWrapper from "./Components/SocketWrapper"
import IncomingCallPopup from "./Components/IncomingCallPopup"
import GloabalAudio from "./Components/GlobalAudio"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "PulseChat",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <SessionWrapper>
        <SocketWrapper>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <GloabalAudio/>
            <IncomingCallPopup/>
            {children}
          </body>
        </SocketWrapper>
      </SessionWrapper>
    </html>
  )
}
